### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [leandromartin114/dwf-m8-desafio#1]
Hola @leandromartin114. Felicitaciones!! quedo muy buena la app.  Solo hay 2 cosas que estaria bueno corregir. La primera, es que la app no te marca ningun error si queres reportar info de una mascota y mandas el formulario vacio. Muestra la notificacion de mensaje enviado. Y la segunda, es que estaria bueno q al apretar el boton de "mi ubicacion" para que se muestren las mascotas cerca, en el caso de no haber mascotas, aparezca un texto que diga "no hay mascotas cerca" o algo asi, sino da la impresion de que no funciona el boton.

**Comment by leandromartin114** [comment]
Hola Ale, Muchas gracias por tu review! Había pasado por alto algunos de estos detalles. Ahora sí creo que quedó ok.
Saludos.
