### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by lupattin** [leandromartin114/dwf-m8-desafio#2]
Hola Leandro! como estas?

Te dejo mi revisión!
Primero! felicitaciones por el desafío, creo que de diseño y fluidez esta muy bien! Solo tiene algunos detalles por corregir:

Lo primero, agrego un comentario al otro issue que te dejaron, que es cuando compartís ubicación estaría bueno que aparezca el formulario para logiarte o registrarse, porque sino hasta que no haces click en alguna de las opciones del navbar no te deja hacer el inicio de sesión. Y esto es poco intuitivo.

Segundo error: cuando modificas los datos, no se actualiza el mail modificado arriba a la derecha. Te dejo las imagenes.
![image](https://user-images.githubusercontent.com/88295111/192823776-8b1cac69-163e-4ae0-b177-91f44c9bd37d.png)
![image](https://user-images.githubusercontent.com/88295111/192823808-22203975-2156-47f1-b977-e893640072c7.png)

Tercer error: cuando reportas una mascota y volves al inicio, no te aparece automáticamente la mascota reportada, sino que tenes que apretar de nuevo para compartir ubicación y recién ahí aparece. El problema es que al inicio de la pagina ya había compartido la ubicación por lo que no debería hacer falta volver a apretar el botón de ubicación. 

Después, no encontré mas errores. Cualquier ayuda que necesites apoyate en discord!

Saludos!

**Comment by leandromartin114** [comment]
Hola Luca, ya quedaron los errores solucionados. Muchas gracias por la devolución! Saludos.
