### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [leandromartin114/dwf-m8-desafio#3]
Buenas Leandro!
Felicitaciones por llegar hasta acá.
Sumado a los comentarios que te dejaron en otros issues, no pude lograr cargar una imagen al reportar una mascota.
Te dejo el error que me tira: 

Failed to load resource: the server responded with a status of 400 (Bad Request)
dwf-m7-petfinder.herokuapp.com/report/44:1

**Comment by leandromartin114** [comment]
Hola Fer gracias por la review! No me aparece este error que comentas. Tanto en local como en producción no me ha arrojado este error. Ya arreglé otros inconvenientes que me habían marcado y por el momento la veo funcionando ok. Si podés te fijas de nuevo porfa. Saludos.
